### ISSUE TITLE
Contraste améliorable

### ISSUE THREAD

**Issue by pinage404** [nicokosi/nicokosi.github.io#1]
Dans le header, le contraste entre le texte et le background est améliorable

![image](https://user-images.githubusercontent.com/6325757/111372156-93f00b80-869a-11eb-8174-3ced75f7321e.png)

---

Je pense que c'est lié à [cette option](https://github.com/gilsondev/pelican-clean-blog#header-color) qui semble etre définie à `HEADER_COLOR = 'PowderBlue'`

**Comment by nicokosi** [comment]
Merci @pinage404 pour ton retour (je viens d'en prendre connaissance 😭). Je vais regarder ça... ⏳

**Comment by nicokosi** [comment]
> Merci @pinage404 pour ton retour (je viens d'en prendre connaissance 😭). Je vais regarder ça... ⏳

J'ai essayé de personnaliser le style de l'en-tête mais je n'ai pas réussi (je suis nul en CSS 😅).
J'ai lancé une bouteille à la mer en ouvrant ce ticket : https://github.com/gilsondev/pelican-clean-blog/issues/83 🤷

**Comment by nicokosi** [comment]
Est-ce que c'est mieux ainsi ?
<img width="1381" alt="Screenshot 2021-11-15 at 06 10 17" src="https://user-images.githubusercontent.com/3862051/141727486-b78bd9ea-25db-4dd6-bb58-25b7bd0f2c79.png">
